persistence:
  enabled: true
  size: 5Gi
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  enabled: true
  path: /
  hosts:
    - docker-registry.apps-hosting.com
  tls:
    - hosts:
        - docker-registry.apps-hosting.com
      secretName: tls-wildcard.apps-hosting.com